version: '3.7'
name: med-planner

networks:
  med-planner-network:
    driver: bridge

volumes:
  postgres-med-planner-data:
    external: false
  test-postgres-med-planner-data:
    external: false

services:
  postgres-med-planner:
    image: postgres:16.0-alpine
    container_name: postgres-med-planner
    hostname: postgres-med-planner
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_pass
      POSTGRES_DB: med_planner_db
      PGTZ: America/Sao_Paulo
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres-med-planner-data:/var/lib/postgresql/data
    command: postgres -c timezone=America/Sao_Paulo
    networks:
      - med-planner-network

  test-postgres-med-planner:
    image: postgres:16.0-alpine
    container_name: test-postgres-med-planner
    hostname: test-postgres-med-planner
    environment:
      POSTGRES_USER: api_user_test
      POSTGRES_PASSWORD: api_pass_test
      POSTGRES_DB: med_planner_db_test
      PGTZ: America/Sao_Paulo
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    volumes:
      - test-postgres-med-planner-data:/var/lib/postgresql/data
    command: postgres -c timezone=America/Sao_Paulo
    networks:
      - med-planner-network

  backend-rest:
    build:
      context: ./backend-rest
      dockerfile: Dockerfile
    depends_on:
      - postgres-med-planner
    container_name: backend-rest
    hostname: backend-rest
    ports:
      - "3000:3000"
    tty: true
    networks:
      - med-planner-network
