name: TESTES_CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  JSON_SECRET : ${{ secrets.JSON_SECRET }}
  TZ : America/Sao_Paulo
  DB_NAME : med_planner_db
  DB_USER : api_user
  DB_PWD : api_pass
  DB_HOST : postgres-med-planner
  DB_PORT : 5432
  DB_DIALECT : postgres
  DB_TIMEZONE : America/Sao_Paulo
  DB_TEST_NAME : med_planner_db_test
  DB_TEST_USER : api_user_test
  DB_TEST_PWD : api_pass_test
  DB_TEST_HOST : localhost
  DB_TEST_PORT : 5432
  DB_TEST_DIALECT : postgres
  DB_TEST_TIMEZONE : America/Sao_Paulo

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: api_user_test
          POSTGRES_PASSWORD: api_pass_test
          POSTGRES_DB: med_planner_db_test
          PGTZ: America/Sao_Paulo
          TZ: America/Sao_Paulo

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./backend-rest
        run: npm install

      - name: Run Tests in backend-rest
        working-directory: ./backend-rest
        run: npm run test
